image: ruby:2.2.3
script:
  - mkdir -p /tmp/bundle
  - bundle install --quiet --path /tmp/bundle
  - bundle exec rspec spec
cache:
  - /tmp/bundle
services:
  - mongodb
  - redis
branches:
  - master
  - dev
deploy:
  bash:
    script:
      #- bundle exec cap production deploy
notify:
  email:
    recipients:
      - wazery@ubuntu.com
