api:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports: 
    - "3000:3000"
  links: 
    - database
    - redis
  volumes:
    - .:/hackhub

database:
  image: mongo
  ports: 
    - "27017:27017"

redis:
  image: redis:3.0.4
  ports:
    - "6379":"6379"
